name: traindown
description: A language to help athletes express their training. Inspired by Markdown.
homepage: https://www.traindown.com/
version: 2.4.1
environment:
  sdk: ">=2.2.0 <3.0.0"
dependencies:
  characters: ^1.0.0
dev_dependencies:
  pedantic:
  mockito:
  test:
