name: traindown
description: A language to help athletes express their training. Inspired by Markdown.
homepage: https://www.traindown.com/
version: 1.4.0
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
dev_dependencies:
  pedantic:
  mockito:
  test:
