name: traindown
description: A language to help athletes express their training. Inspired by Markdown.
homepage: https://www.traindown.com/
version: 3.1.0
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  characters: ^1.1.0
dev_dependencies:
  pedantic: ^1.11.0
  mockito: ^5.0.10
  test: ^1.17.5
