name: traindown
description: A language to help athletes express their training. Inspired by Markdown.
homepage: https://www.traindown.com/
version: 1.0.0
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  args: ^1.6.0
  shelf: ^0.7.5
dev_dependencies:
  pedantic:
  mockito:
  test:
